# Generated by Django 5.0.3 on 2024-06-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D2L', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
